VKEY_NONE    = 0;
VKEY_BACK    = 8;
VKEY_TAB     = 9;

VKEY_ENTER   = 13;
VKEY_PGUP    = 14;
VKEY_PGDOWN  = 15;
VKEY_END     = 16;
VKEY_HOME    = 17;
VKEY_LEFT    = 18;
VKEY_UP      = 19;
VKEY_RIGHT   = 20;
VKEY_DOWN    = 21;
VKEY_DELETE  = 22;
VKEY_INSERT  = 23;
VKEY_CENTER  = 24;

VKEY_ESCAPE  = 27;

VKEY_SPACE   = 32;

VKEY_QUOTE   = 39;

VKEY_COMMA   = 44;
VKEY_MINUS   = 45;
VKEY_PERIOD  = 46;
VKEY_SLASH   = 47;

VKEY_0       = 48;
VKEY_1       = 49;
VKEY_2       = 50;
VKEY_3       = 51;
VKEY_4       = 52;
VKEY_5       = 53;
VKEY_6       = 54;
VKEY_7       = 55;
VKEY_8       = 56;
VKEY_9       = 57;

VKEY_SCOLON  = 59;
VKEY_EQUALS  = 61;

VKEY_LBRACKET= 91;
VKEY_BSLASH  = 92;
VKEY_RBRACKET= 93;

VKEY_BQUOTE  = 96;
VKEY_A       = 97;
VKEY_B       = 98;
VKEY_C       = 99;
VKEY_D       =100;
VKEY_E       =101;
VKEY_F       =102;
VKEY_G       =103;
VKEY_H       =104;
VKEY_I       =105;
VKEY_J       =106;
VKEY_K       =107;
VKEY_L       =108;
VKEY_M       =109;
VKEY_N       =110;
VKEY_O       =111;
VKEY_P       =112;
VKEY_Q       =113;
VKEY_R       =114;
VKEY_S       =115;
VKEY_T       =116;
VKEY_U       =117;
VKEY_V       =118;
VKEY_W       =119;
VKEY_X       =120;
VKEY_Y       =121;
VKEY_Z       =122;


VKEY_F1  = 131;
VKEY_F2  = 132;
VKEY_F3  = 133;
VKEY_F4  = 134;
VKEY_F5  = 135;
VKEY_F6  = 136;
VKEY_F7  = 137;
VKEY_F8  = 138;
VKEY_F9  = 139;
VKEY_F10 = 140;
VKEY_F11 = 141;
VKEY_F12 = 142;

